import { useState } from 'react'
import { useData } from '../hooks/useData'
import { useProject } from '../hooks/useProject'
import { useAuth } from '../hooks/useAuth'
import { callClaude, callGPT } from '../lib/ai'
import { getSystemPrompt, isUSACE, getTerm, getPrintHeader, getPrintFooter } from '../data/standards'
import { SC, Card, LD, Empty, DelBtn, FrameworkBadge, fmtMd } from '../components/SharedUI'

export function JHABuilder() {
  const { user } = useAuth()
  const { activeProject } = useProject()
  const { data: jhas, add, update, remove, loading } = useData<any>('jhas')
  const [showForm, setShowForm] = useState(false)
  const [aiResult, setAiResult] = useState('')
  const [peerReview, setPeerReview] = useState('')
  const [generating, setGenerating] = useState(false)
  const [reviewing, setReviewing] = useState(false)
  const [aiDesc, setAiDesc] = useState('')
  const [expanded, setExpanded] = useState<string | null>(null)

  const usace = isUSACE(activeProject?.framework)
  const docType = usace ? 'AHA' : 'JHA'
  const docTypeFull = usace ? 'Activity Hazard Analysis' : 'Job Hazard Analysis'
  const sysPrompt = getSystemPrompt(activeProject?.framework)

  const handleManualSave = async (e: React.FormEvent<HTMLFormElement>) => {
    e.preventDefault()
    const fd = new FormData(e.currentTarget)
    const steps = (fd.get('steps') as string).split('\n').filter(l => l.trim().length > 2).map(s => ({ step: s.replace(/^\d+[.)]\s*/, ''), hazards: 'Not yet analyzed', controls: 'Not yet analyzed' }))
    await add({
      activity: fd.get('activity'), location: fd.get('location') || activeProject?.location || '',
      environment: fd.get('environment'), framework: activeProject?.framework || 'OSHA',
      competent_person: fd.get('competent'), ppe: fd.get('ppe'),
      steps: JSON.stringify(steps), status: 'Draft', ai_generated: false,
      project_id: activeProject?.id || '', created_by: user?.user_metadata?.name || user?.email || '',
      created_at: new Date().toISOString()
    })
    setShowForm(false)
  }

  // ═══ STEP 1: Claude generates the JHA/AHA ═══
  const generateAI = async () => {
    if (!aiDesc) { alert('Describe the work activity.'); return }
    setGenerating(true); setAiResult(''); setPeerReview('')

    // Use a condensed prompt to stay under Netlify's 10s timeout
    const condensedPrompt = usace
      ? `You are a USACE EM 385-1-1 safety expert. Generate an Activity Hazard Analysis (AHA) per Section 01.A.14. Cite EM 385 sections. Include RAC codes (1-5), Competent Persons, and Three-Phase Inspection requirements.`
      : `You are a construction safety expert. Generate a Job Hazard Analysis with OSHA citations. Use WHAT-WHY-HOW framework.`

    const prompt = `${condensedPrompt}\n\nGenerate a ${docTypeFull} for:\nACTIVITY: ${aiDesc}\nPROJECT: ${activeProject?.name || 'General'} — ${activeProject?.city || ''}, ${activeProject?.state || ''}\nFRAMEWORK: ${activeProject?.framework || 'OSHA'}\n\nFor each step: hazards, controls (engineering→admin→PPE), responsible person, citation${usace ? ', RAC code' : ''}.\nInclude: PPE list, permits needed, emergency procedures, STOP WORK triggers.`

    try {
      const data = await callClaude([{ role: 'user', content: prompt }], 4000)
      setAiResult(data.content?.[0]?.text || 'No response')
    } catch (e: any) { setAiResult('Error: ' + e.message) }
    setGenerating(false)
  }

  // ═══ STEP 2: GPT-4o peer reviews Claude's JHA/AHA ═══
  const runPeerReview = async () => {
    if (!aiResult) return
    setReviewing(true); setPeerReview('')

    const reviewPrompt = `You are an independent safety peer reviewer. A ${docTypeFull} was generated by another AI model. Your job is to CRITICALLY REVIEW it and identify:

1. MISSED HAZARDS — What hazards did the original ${docType} fail to identify?
2. INADEQUATE CONTROLS — Where are controls insufficient or not following the hierarchy (engineering → admin → PPE)?
3. MISSING CITATIONS — What standard references are missing or incorrect?
4. GAPS IN SEQUENCE — Are any work steps missing or out of order?
5. PPE GAPS — Is the PPE list complete for all identified hazards?
6. STOP WORK GAPS — Are there stop work triggers that should be added?
${usace ? '7. EM 385 COMPLIANCE — Does this AHA meet EM 385-1-1 Section 01.A.14 requirements? Are RAC codes accurate? Are Competent Persons identified for each step?' : ''}

ACTIVITY: ${aiDesc}
FRAMEWORK: ${activeProject?.framework || 'OSHA'}

${docType} TO REVIEW:
${aiResult.substring(0, 5000)}

Provide your review as:
## PEER REVIEW SUMMARY
- Overall Rating: ACCEPTABLE / NEEDS REVISION / INADEQUATE
- Critical gaps found: [count]

## MISSED HAZARDS
## INADEQUATE CONTROLS
## MISSING CITATIONS
## RECOMMENDED ADDITIONS
## FINAL ASSESSMENT`

    try {
      // Use GPT-4o as the peer reviewer
      const gptRes = await callGPT([{ role: 'user', content: reviewPrompt }], 3000)
      if (gptRes?.choices?.[0]?.message?.content) {
        setPeerReview(gptRes.choices[0].message.content)
      } else {
        // Fallback: use Claude with a reviewer persona if GPT fails
        const fallback = await callClaude([{ role: 'user', content: `You are a DIFFERENT safety expert than the one who wrote this ${docType}. ${reviewPrompt}` }], 3000)
        setPeerReview(fallback.content?.[0]?.text || 'Peer review unavailable.')
      }
    } catch (e: any) { setPeerReview('Peer review error: ' + e.message) }
    setReviewing(false)
  }

  const saveAIJHA = async () => {
    if (!aiResult) return
    await add({
      activity: aiDesc, location: activeProject?.location || '', environment: 'General Construction',
      framework: activeProject?.framework || 'OSHA', competent_person: '', ppe: 'See AI analysis',
      steps: '[]', content: aiResult, peer_review: peerReview || null,
      status: peerReview ? 'Peer Reviewed' : 'Draft', ai_generated: true,
      project_id: activeProject?.id || '', created_by: user?.user_metadata?.name || '',
      created_at: new Date().toISOString()
    })
    setAiDesc(''); setAiResult(''); setPeerReview('')
  }

  const printJHA = (j: any) => {
    const w = window.open('', '', 'width=900,height=700'); if (!w) return
    const borderColor = usace ? '#065f46' : '#f97316'
    w.document.write(`<html><head><title>${docType}</title><style>body{font-family:Arial,sans-serif;padding:2rem;font-size:12px}h1{font-size:18px;border-bottom:2px solid ${borderColor};padding-bottom:8px}table{width:100%;border-collapse:collapse;margin:8px 0}th,td{border:1px solid #ccc;padding:6px;text-align:left}th{background:#f5f5f5}.review{margin-top:16px;padding:12px;background:#fffbeb;border:1px solid #f59e0b;border-radius:6px}.sig{margin-top:30px;display:flex;gap:40px}.sig div{border-top:1px solid #333;padding-top:4px;min-width:150px;font-size:11px;margin-top:24px}@media print{body{padding:0}}</style></head><body>`)
    if (usace) w.document.write(getPrintHeader(activeProject?.framework))
    w.document.write(`<h1>${usace ? 'ACTIVITY HAZARD ANALYSIS (AHA)' : 'JOB HAZARD ANALYSIS (JHA)'}</h1>`)
    w.document.write(`<table><tr><td><b>Activity:</b> ${j.activity}</td><td><b>Date:</b> ${new Date(j.created_at).toLocaleDateString()}</td></tr><tr><td><b>Location:</b> ${j.location || '—'}</td><td><b>Framework:</b> ${j.framework || 'OSHA'}</td></tr><tr><td><b>${usace ? 'SSHO' : 'Competent Person'}:</b> ${j.competent_person || 'TBD'}</td><td><b>Status:</b> ${j.status}</td></tr>${usace ? `<tr><td><b>Contract #:</b> _______________</td><td><b>CQM Approved:</b> ☐ Yes ☐ No</td></tr>` : ''}</table>`)
    if (j.content) w.document.write(`<div style="white-space:pre-line;margin-top:16px;line-height:1.6">${j.content}</div>`)
    if (j.peer_review) w.document.write(`<div class="review"><h3 style="font-size:13px;color:#b45309;margin:0 0 8px">🔍 Dual AI Peer Review (GPT-4o)</h3><div style="white-space:pre-line;line-height:1.5">${j.peer_review}</div></div>`)
    const sigLabels = usace ? ['SSHO','Superintendent','CQM Manager','Contracting Officer','Date'] : ['Competent Person','Superintendent','Safety Manager','Date']
    w.document.write(`<div class="sig">${sigLabels.map(l => `<div>${l}</div>`).join('')}</div>`)
    w.document.write(getPrintFooter(activeProject?.framework))
    w.document.write('</body></html>')
    w.document.close(); w.print()
  }

  return (
    <div className="p-6 max-w-5xl mx-auto">
      <div className="flex justify-between items-center mb-5">
        <div>
          <h1 className="text-2xl font-extrabold">{docType} Builder</h1>
          <p className="text-sm" style={{ color: 'var(--t3)' }}>AI-powered {docTypeFull} with Dual-Model Peer Review — {activeProject?.name || 'All Projects'}</p>
        </div>
        <div className="flex gap-2">
          <FrameworkBadge framework={activeProject?.framework} />
          <button onClick={() => setShowForm(!showForm)} className="px-4 py-2 rounded-lg font-bold text-sm text-white" style={{ background: 'linear-gradient(135deg, #f97316, #fb923c)' }}>+ Manual {docType}</button>
        </div>
      </div>

      <div className="grid grid-cols-5 gap-3 mb-4">
        <SC label="Total" value={jhas.length} color="var(--acc)" />
        <SC label="Approved" value={jhas.filter((j: any) => j.status === 'Approved').length} color="var(--grn)" />
        <SC label="Peer Reviewed" value={jhas.filter((j: any) => j.status === 'Peer Reviewed').length} color="var(--pur)" />
        <SC label="Draft" value={jhas.filter((j: any) => j.status === 'Draft').length} color="var(--yel)" />
        <SC label="AI Generated" value={jhas.filter((j: any) => j.ai_generated).length} color="var(--blu)" />
      </div>

      {/* AI Generator */}
      <div className="rounded-xl p-5 mb-4" style={{ background: 'var(--bg2)', border: '1px solid var(--bdr)', borderLeft: '3px solid var(--blu)' }}>
        <h3 className="font-bold text-sm mb-2">🤖 AI {docType} Generator — Dual Model</h3>
        <p className="text-xs mb-3" style={{ color: 'var(--t3)' }}>Step 1: Claude generates the {docType} → Step 2: GPT-4o peer reviews for gaps and missed hazards</p>
        <textarea value={aiDesc} onChange={e => setAiDesc(e.target.value)} rows={2}
          placeholder={usace ? 'Installing structural steel beams at 40ft using 150-ton crawler crane — definable feature of work...' : 'Installing structural steel beams at 40 feet using a 150-ton crawler crane...'}
          className="w-full px-3 py-2 rounded-lg text-sm resize-y mb-2" style={{ background: 'var(--bg3)', color: 'var(--t1)', border: '1.5px solid var(--bdr)' }} />

        <div className="flex gap-2">
          <button onClick={generateAI} disabled={generating}
            className="flex-1 py-2 rounded-lg font-bold text-sm text-white"
            style={{ background: generating ? 'var(--bg3)' : 'linear-gradient(135deg, #8b5cf6, #a78bfa)', opacity: generating ? 0.6 : 1 }}>
            {generating ? 'Claude is generating...' : `Step 1: Generate ${docType} (Claude)`}
          </button>
          {aiResult && (
            <button onClick={runPeerReview} disabled={reviewing}
              className="flex-1 py-2 rounded-lg font-bold text-sm text-white"
              style={{ background: reviewing ? 'var(--bg3)' : 'linear-gradient(135deg, #3b82f6, #60a5fa)', opacity: reviewing ? 0.6 : 1 }}>
              {reviewing ? 'GPT-4o reviewing...' : peerReview ? '🔄 Re-run Peer Review' : `Step 2: Peer Review (GPT-4o)`}
            </button>
          )}
        </div>

        {/* Claude's JHA/AHA */}
        {aiResult && (
          <div className="mt-3">
            <div className="text-xs font-semibold mb-1" style={{ color: 'var(--pur)' }}>Claude — {docType} Draft</div>
            <div className="ai-result text-sm leading-relaxed max-h-80 overflow-y-auto p-3 rounded-lg" style={{ background: 'var(--bg3)', color: 'var(--t2)' }} dangerouslySetInnerHTML={{ __html: fmtMd(aiResult) }} />
          </div>
        )}

        {/* GPT-4o Peer Review */}
        {peerReview && (
          <div className="mt-3">
            <div className="text-xs font-semibold mb-1" style={{ color: 'var(--blu)' }}>🔍 GPT-4o — Peer Review</div>
            <div className="ai-result text-sm leading-relaxed max-h-80 overflow-y-auto p-3 rounded-lg" style={{ background: 'rgba(59,130,246,.04)', color: 'var(--t2)', border: '1px solid rgba(59,130,246,.2)' }} dangerouslySetInnerHTML={{ __html: fmtMd(peerReview) }} />
          </div>
        )}

        {aiResult && (
          <div className="flex gap-2 mt-3">
            <button onClick={saveAIJHA} className="px-5 py-2 rounded-lg font-bold text-sm text-white" style={{ background: 'linear-gradient(135deg, #f97316, #fb923c)' }}>
              Save {docType} {peerReview ? '(with Peer Review)' : '(Draft)'}
            </button>
            {!peerReview && <span className="text-xs self-center" style={{ color: 'var(--yel)' }}>⚠️ Run peer review before saving for best results</span>}
          </div>
        )}
      </div>

      {/* Manual Form */}
      {showForm && (
        <form onSubmit={handleManualSave} className="rounded-xl p-5 mb-4" style={{ background: 'var(--bg2)', border: '1px solid var(--acc)' }}>
          <h3 className="font-bold text-sm mb-3">Manual {docType}</h3>
          <div className="grid grid-cols-2 gap-3">
            <div><label className="block text-xs font-semibold uppercase tracking-wider mb-1" style={{ color: 'var(--t3)' }}>Activity</label><input name="activity" required placeholder="Steel erection" className="w-full px-3 py-2 rounded-lg text-sm" style={{ background: 'var(--bg3)', color: 'var(--t1)', border: '1.5px solid var(--bdr)' }} /></div>
            <div><label className="block text-xs font-semibold uppercase tracking-wider mb-1" style={{ color: 'var(--t3)' }}>Location</label><input name="location" placeholder={activeProject?.location || ''} className="w-full px-3 py-2 rounded-lg text-sm" style={{ background: 'var(--bg3)', color: 'var(--t1)', border: '1.5px solid var(--bdr)' }} /></div>
            <div><label className="block text-xs font-semibold uppercase tracking-wider mb-1" style={{ color: 'var(--t3)' }}>Environment</label><select name="environment" className="w-full px-3 py-2 rounded-lg text-sm" style={{ background: 'var(--bg3)', color: 'var(--t1)', border: '1.5px solid var(--bdr)' }}><option>General Construction</option><option>Industrial</option><option>Marine</option><option>Confined Space</option><option>Elevated</option></select></div>
            <div><label className="block text-xs font-semibold uppercase tracking-wider mb-1" style={{ color: 'var(--t3)' }}>{usace ? 'SSHO / Competent Person' : 'Competent Person'}</label><input name="competent" className="w-full px-3 py-2 rounded-lg text-sm" style={{ background: 'var(--bg3)', color: 'var(--t1)', border: '1.5px solid var(--bdr)' }} /></div>
            <div className="col-span-2"><label className="block text-xs font-semibold uppercase tracking-wider mb-1" style={{ color: 'var(--t3)' }}>Steps (one per line)</label><textarea name="steps" rows={4} placeholder={"1. Set up barricades\n2. Inspect rigging\n3. Signal crane"} className="w-full px-3 py-2 rounded-lg text-sm resize-y" style={{ background: 'var(--bg3)', color: 'var(--t1)', border: '1.5px solid var(--bdr)' }} /></div>
            <div className="col-span-2"><label className="block text-xs font-semibold uppercase tracking-wider mb-1" style={{ color: 'var(--t3)' }}>PPE Required</label><input name="ppe" placeholder="Hard hat, harness, steel-toes, gloves" className="w-full px-3 py-2 rounded-lg text-sm" style={{ background: 'var(--bg3)', color: 'var(--t1)', border: '1.5px solid var(--bdr)' }} /></div>
          </div>
          <div className="flex gap-2 mt-3">
            <button type="submit" className="px-5 py-2 rounded-lg font-bold text-sm text-white" style={{ background: 'linear-gradient(135deg, #f97316, #fb923c)' }}>Save {docType}</button>
            <button type="button" onClick={() => setShowForm(false)} className="px-4 py-2 rounded-lg text-sm" style={{ border: '1px solid var(--bdr)', color: 'var(--t3)' }}>Cancel</button>
          </div>
        </form>
      )}

      {/* JHA/AHA List */}
      {loading ? <LD /> : jhas.length === 0 ? <Empty msg={`No ${docType}s yet. Generate one with AI or create manually.`} icon="📝" /> :
        jhas.map((j: any) => (
          <Card key={j.id} borderColor={j.status === 'Approved' ? 'var(--grn)' : j.status === 'Peer Reviewed' ? 'var(--pur)' : 'var(--yel)'}>
            <div className="flex justify-between items-center">
              <div className="flex items-center gap-2">
                <span className="font-semibold">{j.activity}</span>
                <span className="text-xs px-2 py-0.5 rounded font-semibold" style={{
                  background: j.status === 'Approved' ? 'rgba(34,197,94,.12)' : j.status === 'Peer Reviewed' ? 'rgba(139,92,246,.12)' : 'rgba(251,191,36,.12)',
                  color: j.status === 'Approved' ? 'var(--grn)' : j.status === 'Peer Reviewed' ? 'var(--pur)' : 'var(--yel)'
                }}>{j.status}</span>
                {j.ai_generated && <span className="text-xs" style={{ color: 'var(--blu)' }}>🤖 AI</span>}
                {j.peer_review && <span className="text-xs" style={{ color: 'var(--pur)' }}>🔍 Reviewed</span>}
              </div>
              <div className="flex gap-1">
                <button onClick={() => setExpanded(expanded === j.id ? null : j.id)} className="px-2 py-1 rounded text-xs" style={{ border: '1px solid var(--bdr)', color: 'var(--t3)' }}>View</button>
                {j.status !== 'Approved' && <button onClick={() => update(j.id, { status: 'Approved', approved_by: user?.user_metadata?.name, approved_at: new Date().toISOString() })} className="px-2 py-1 rounded text-xs" style={{ border: '1px solid var(--grn)', color: 'var(--grn)' }}>Approve</button>}
                <button onClick={() => printJHA(j)} className="px-2 py-1 rounded text-xs" style={{ border: '1px solid var(--blu)', color: 'var(--blu)' }}>Print</button>
                <DelBtn onClick={() => remove(j.id)} />
              </div>
            </div>
            <div className="text-xs mt-1" style={{ color: 'var(--t3)' }}>{j.environment || '—'} | {j.framework || 'OSHA'} | {new Date(j.created_at).toLocaleDateString()}</div>
            {expanded === j.id && (
              <div className="mt-2">
                {j.content && <div className="ai-result text-sm leading-relaxed max-h-96 overflow-y-auto p-3 rounded-lg mb-2" style={{ background: 'var(--bg3)', color: 'var(--t2)' }} dangerouslySetInnerHTML={{ __html: fmtMd(j.content) }} />}
                {j.peer_review && (
                  <div className="p-3 rounded-lg" style={{ background: 'rgba(59,130,246,.04)', border: '1px solid rgba(59,130,246,.2)' }}>
                    <div className="text-xs font-semibold mb-1" style={{ color: 'var(--blu)' }}>🔍 Peer Review</div>
                    <div className="text-sm leading-relaxed max-h-60 overflow-y-auto" style={{ color: 'var(--t2)' }} dangerouslySetInnerHTML={{ __html: fmtMd(j.peer_review) }} />
                  </div>
                )}
              </div>
            )}
          </Card>
        ))
      }
    </div>
  )
}
